print("hello world, learn python ")
print("***************************")
print("FIRST PROGRAM-PYTHON PRINT FUNCTION\nit is declared like this:\nprint('what to print') ")
print("***************************")
print("second way printing:")
print("FIRST PROGRAM-PYTHON PRINT FUNCTION")
print("it is declared like this:")
print("print('what to print') ")
print("***************************")