f = open('output.txt', 'w')
f.write('Hello, World!\n')
f.write('This is a test file.\n')
f.write('Goodbye!\n')
f.close()
f = open('output.txt', 'r')
print(f.read())
f.close()
f = open('text.txt', 'a')
f.write('This is an appended line.\n')
f.close()
f = open('text.txt', 'r')
print(f.read())
f.close()